### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by alexanderosmith** [hugodecasta/ZRMconnector#1]
I ran "node ." and got the following error:

`ZRMconnector/connector.js:102
                let paper = papers[title] ?? { title }
                                           ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aos11409/ZRMconnector/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

I'm unsure if this is my fault in setting up the connectors.json or if this is a error in the main code. Any ideas?

**Comment by hugodecasta** [comment]
yeah you need at least node 15 to run this one
